language: node_js
node_js:
  - 12.18.1
cache: npm
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  local_dir: public
  target_branch: gh-pages
  on:
    branch: main